# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlSnap < Formula
  desc "Delete half of the pods in a Kubernetes cluster or namespace"
  homepage "https://github.com/sanderploegsma/kubectl-snap"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.4.0/kubectl-snap_0.4.0_darwin_arm64.tar.gz"
      sha256 "12cc7e0c5e66ed71b3a4755eef77a7080def015322844e263e31314c8b3e0d1d"

      def install
        bin.install "kubectl-snap"
        bin.install "kubectl_complete-snap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.4.0/kubectl-snap_0.4.0_darwin_amd64.tar.gz"
      sha256 "5eb1739cbfcebadd9f4e24e7c1bbe71c3765e6c0db978682ae0f917a2c83d6de"

      def install
        bin.install "kubectl-snap"
        bin.install "kubectl_complete-snap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.4.0/kubectl-snap_0.4.0_linux_arm64.tar.gz"
      sha256 "98df90eff37e67a2c937f4d21ea367f82fdfc221b44a84c864c31f73af6ca5bc"

      def install
        bin.install "kubectl-snap"
        bin.install "kubectl_complete-snap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.4.0/kubectl-snap_0.4.0_linux_amd64.tar.gz"
      sha256 "197d985c7bfd8529d77d5917112e24444d2a9f1c0beb2b61df8fc7c0a8d794d8"

      def install
        bin.install "kubectl-snap"
        bin.install "kubectl_complete-snap"
      end
    end
  end
end
