# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlSnap < Formula
  desc "Delete half of the pods in a Kubernetes cluster or namespace"
  homepage "https://github.com/sanderploegsma/kubectl-snap"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.1.0/kubectl-snap_0.1.0_darwin_amd64.tar.gz"
      sha256 "d669ea6e3f05c85679dd35bf73bcb11fb17f2137d90e521aeceaa942078e8cef"

      def install
        bin.install "kubectl-snap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.1.0/kubectl-snap_0.1.0_darwin_arm64.tar.gz"
      sha256 "3cfa0645c25337615526dd4303dbe5b19f0241452af6743571218dac2a87c5a2"

      def install
        bin.install "kubectl-snap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.1.0/kubectl-snap_0.1.0_linux_arm64.tar.gz"
      sha256 "ab9733777afe058070477a3bb3d1ff2f652add68b899f337280d2369226a6422"

      def install
        bin.install "kubectl-snap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.1.0/kubectl-snap_0.1.0_linux_amd64.tar.gz"
      sha256 "751071cb03cc3f006ec3f12312c33ee27079d71b965eb498e0c6e226f92e34e9"

      def install
        bin.install "kubectl-snap"
      end
    end
  end
end
