# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlSnap < Formula
  desc "Delete half of the pods in a Kubernetes cluster or namespace"
  homepage "https://github.com/sanderploegsma/kubectl-snap"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.4.1/kubectl-snap_0.4.1_darwin_amd64.tar.gz"
      sha256 "6a69adbe6687b22a45608319c2dd9e20c354c93ab7f6fdc08287cd9fb0130e42"

      def install
        bin.install "kubectl-snap"
        bin.install "kubectl_complete-snap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.4.1/kubectl-snap_0.4.1_darwin_arm64.tar.gz"
      sha256 "6d620b7b81ad073bff0929350760896730f311db075d06256c44bf193c380c08"

      def install
        bin.install "kubectl-snap"
        bin.install "kubectl_complete-snap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.4.1/kubectl-snap_0.4.1_linux_amd64.tar.gz"
        sha256 "e5deda2b45e26bdfedef41337a7c2111208fddb029cf2f73bdd89166e20c7548"

        def install
          bin.install "kubectl-snap"
          bin.install "kubectl_complete-snap"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.4.1/kubectl-snap_0.4.1_linux_armv6.tar.gz"
        sha256 "e91fdd2161e2d7bbe7251ba164ed977974b8871d62bb0a1765227d26f554be24"

        def install
          bin.install "kubectl-snap"
          bin.install "kubectl_complete-snap"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sanderploegsma/kubectl-snap/releases/download/v0.4.1/kubectl-snap_0.4.1_linux_arm64.tar.gz"
        sha256 "a5a8288236000e40f32aa9ff7a9b1c37363de2ba382e604b0ec1fcfb91d6f5c0"

        def install
          bin.install "kubectl-snap"
          bin.install "kubectl_complete-snap"
        end
      end
    end
  end
end
