# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Serve static content in a jiffy"
  homepage "https://github.com/sanderploegsma/serve"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sanderploegsma/serve/releases/download/v0.1.0/serve_0.1.0_darwin_arm64.tar.gz"
      sha256 "f0b0875d4be7887fda25acea3799d49a0f8feea0fb899814ce41c9fc67ce897d"

      def install
        bin.install "serve"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sanderploegsma/serve/releases/download/v0.1.0/serve_0.1.0_darwin_amd64.tar.gz"
      sha256 "962df4808b3f3343f91bb983e5dacbea85eda768f40d787a46c706e68b358862"

      def install
        bin.install "serve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanderploegsma/serve/releases/download/v0.1.0/serve_0.1.0_linux_arm64.tar.gz"
      sha256 "84a074e16548b202b6a98837dce03fdb4a880b80b700b1bd809d74d5060d45bc"

      def install
        bin.install "serve"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sanderploegsma/serve/releases/download/v0.1.0/serve_0.1.0_linux_amd64.tar.gz"
      sha256 "76dd0782d82b6a05ffa6b4b5b9ecd0dd4e3c4cf3df360a345ff913c02c2bb14b"

      def install
        bin.install "serve"
      end
    end
  end
end
