# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TransipDyndns < Formula
  desc "Automatically update DNS entries in your TransIP domain with your current public IP address"
  homepage "https://github.com/sanderploegsma/transip-dyndns"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/sanderploegsma/transip-dyndns/releases/download/v1.0.0/transip-dyndns_Darwin_x86_64.tar.gz"
      sha256 "8107eae8b5e12d697280c582ddc45ef4ff39c5efdf2418a6a3e32de605338bcc"

      def install
        bin.install "transip-dyndns"
      end
    end
    on_arm do
      url "https://github.com/sanderploegsma/transip-dyndns/releases/download/v1.0.0/transip-dyndns_Darwin_arm64.tar.gz"
      sha256 "d1ff92f221f2adc31c2c7e03b3f02a9131f743db431cf989d71dac34c2d2fe50"

      def install
        bin.install "transip-dyndns"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sanderploegsma/transip-dyndns/releases/download/v1.0.0/transip-dyndns_Linux_x86_64.tar.gz"
        sha256 "2042837df8102f80651ebaed883561562fa42169825d06f5e5e3e462bf397893"

        def install
          bin.install "transip-dyndns"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sanderploegsma/transip-dyndns/releases/download/v1.0.0/transip-dyndns_Linux_arm64.tar.gz"
        sha256 "eb8c3ffbd922b38bf79d9cb40578d478f2b1eef649a13a73d580b2dd0a09be27"

        def install
          bin.install "transip-dyndns"
        end
      end
    end
  end

  test do
    system "#{bin}/transip-dyndns --version"
  end
end
